language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update && composer --version
  - composer install

script:
  - php vendor/bin/codecept build
  - php vendor/bin/codecept run
